### ISSUE TITLE
Some blocks do not have any transactions relayer submits transaction from archive

### ISSUE THREAD

**Issue by isSerge** [subspace/subspace-relayer#30] opened 2021-11-04 06:08 UTC
When running Subspace node (+farmer) with relayer processing blocks from archive, some blocks do not have any  transactions:
<img width="836" alt="Screenshot 2021-11-03 at 4 05 04 PM" src="https://user-images.githubusercontent.com/13568875/140266012-c008cdb4-856c-4d44-8b45-f92010d2a2ff.png">
As you can see on the screenshot, there are two gaps: 6-9 and 12-13

**Comment by nazar-pc** [comment] 2021-11-09 21:31
I think this is no longer relevant, closing

**Closed by nazar-pc** 2021-11-09 21:31 UTC

**Comment by isSerge** [comment] 2021-11-10 08:45
screenshot from `aries-dev`, there are still gaps between blocks :
<img width="819" alt="Screenshot 2021-11-10 at 12 42 43 PM" src="https://user-images.githubusercontent.com/13568875/141079754-f5904738-912e-4b2e-8055-372eb12b107a.png">

**Comment by nazar-pc** [comment] 2021-11-10 08:55
I think this is fine now, if one block is skipped than the next one will include bigger batch. We no longer ever have 2 concurrent transactions in tx pool, so by design we might skip some blocks. What matters is the eventual throughput. If it is good enough, we don't need to worry whether particular block has any transactions or now. Also if you can't read disk fast enough to saturate full batch, it will also skip blocks because of that.
